services:
  - type: web
    name: interview-ai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_GEN_AI_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3000
